server:
  port: 9004

spring:
  application:
    name: service-provider
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.242.137:9999 #Nacos服务注册中心地址
    sentinel:
      transport:
        dashboard: 192.168.242.137:8080 #配置Sentinel dashboard地址
        port: 8719

management:
  endpoints:
    web:
      exposure:
        include: '*'