server:
  port: 9002

spring:
  application:
    name: service-provider
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.242.137:8848 #配置Nacos地址

management:
  endpoints:
    web:
      exposure:
        include: '*'
